### ISSUE TITLE
Deleting this repo

### ISSUE THREAD

**Issue by davetcoleman** [ros-planning/moveit_docker#4]
We moved our Docker builds to the main moveit repo a month ago, deprecating this repo. Because this repo is only 3 months old, I'd like to completely delete this repo to reduce confusion and clean the Github org. I'll plan to do this in a month (Oct 16 or later) unless I'm convinced otherwise.

**Comment by IanTheEngineer** [comment]
+1 for deletion. With only two forks / stars, I think it's safe to delete.

**Comment by rhaschke** [comment]
+1

**Comment by v4hn** [comment]
+1 go ahead

**Comment by davetcoleman** [comment]
As announced a month ago, I am deleting moveit_docker right now.
